name: Continuous Deployment

on:
  push: # main 브랜치에 push될 때 실행
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest # 우분투 최신 버전 환경에서 실행

    steps:
      # 코드 checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Vite + React 권장 Node 버전

      # 의존성 설치 및 빌드
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 빌드 파일 전송 (배포 파일 업로드)
      - name: Copy build files
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          source: dist/
          target: /home/ubuntu/13th-fe-ec2/

      # EC2 서버 설정 및 Nginx 재시작
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            sudo systemctl restart nginx